apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-12-3-alpine
spec:
  selector:
    matchLabels:
      app: postgres-12-3-alpine
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: postgres-12-3-alpine
      POSTGRES_PASSWORD: $postgres_password
    spec:
      containers:
      - name: postgres-12-3-alpine
        image: postgres:12.3-alpine
        ports:
        - containerPort: 5432
